---
# tasks file for testClient1
- name: install softs on CentOS
  yum:
    name:
      - vim
      - traceroute
      - tcpdump
      - net-tools
    state: present
    update_cache: true

- name: copy file ifcfg
  copy:
    src: ifcfg-vlan1
    dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
  notify: 
    - restart_network